[1 Example Title]
Latent Growth Curve Model with Time-Varying Covariates

[2. Overview of Model]


[3. Generic Model code]
```{r Example_5-1, eval=FALSE, class.source = 'fold-show'}
# Example-5.1 uses the lavaan package from r
model <- ' i =~ 1*y1 + 1*y2 + 1*y3 + 1*y4
           s =~ 0*y1 + 1*y2 + 2*y3 + 3*y4 '

# time-varying covariates
y1 ~ x1
y2 ~ x2
y3 ~ x3
y4 ~ x4
    
fit <- growth(model, data=path-to-data)
summary(fit)
```


```{r}
# a linear growth model with a time-varying covariate
model <- '
  # intercept and slope with fixed coefficients
    i =~ 1*Brain_T1 + 1*Brain_T2 + 1*Brain_T3 + 1*Brain_T4
    s =~ 0*Brain_T1 + 1*Brain_T2 + 2*Brain_T3 + 3*Brain_T4
  # regressions
    i ~ sex + eduPar
    s ~ sex + eduPar
  # time-varying covariates
    Brain_T1 ~ G_CD
    Brain_T2 ~ IQ
    Brain_T3 ~ age2
    Brain_T4 ~ White
'
fit <- growth(model, data=path-to-data)
summary(fit)
```



[4. Example using ABCD Study data]
"The goal of our current LGM is to assess the linear trajectory of GPA, with the question being, does the average student GPA in a particular school go up or down over time?"

[4a. Model Code]
```{r}
# a linear growth model with a time-varying covariate
model <- '
  # intercept and slope with fixed coefficients
    i =~ 1*Brain_T1 + 1*Brain_T2 + 1*Brain_T3 + 1*Brain_T4
    s =~ 0*Brain_T1 + 1*Brain_T2 + 2*Brain_T3 + 3*Brain_T4
  # regressions
    i ~ sex + eduPar
    s ~ sex + eduPar
  # time-varying covariates
    Brain_T1 ~ G_CD
    Brain_T2 ~ IQ
    Brain_T3 ~ age2
    Brain_T4 ~ White
'
fit <- growth(model, data=path-to-data)
summary(fit)
```









